theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: class-code.fr
  search:
    active: true
  posts:
    list:
      show_categories: false
      truncate_description: 200
  pages:
    list:
      truncate_description: 200
  logo:
    footer: "/assets/images/logo-footer.svg"
  debug:
     productionUrl: "https://www.class-code.fr"