theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: class-code.fr
  search:
    active: true
  posts:
    index:
      options: 
        categories: false
  logo:
    footer: "/assets/images/logo-footer.svg"
  debug:
    productionUrl: "https://www.class-code.fr"